# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_donatur', models.CharField(default='anonim', max_length=1024, verbose_name='nama donatur')),
                ('nilai_donasi', models.CharField(default=0, max_length=1024, verbose_name='nilai donasi')),
                ('status_pembayaran', models.CharField(default='belum terverifikasi', max_length=1024, verbose_name='status pembayaran')),
                ('tanggal_donasi', models.DateField(default=datetime.date.today, verbose_name='tanggal donasi')),
            ],
        ),
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(default='', max_length=1024, verbose_name='nama event')),
                ('deskripsi_event', wagtail.wagtailcore.fields.RichTextField(default='', max_length=1024, verbose_name='deskripsi event')),
                ('tanggal_event', models.DateField(default=datetime.date.today, verbose_name='tanggal event')),
                ('gambar_event_url', models.CharField(blank=True, max_length=1024)),
                ('caption', models.CharField(max_length=1024, verbose_name='caption')),
                ('gambar_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Gallery Pic')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='judul donasi')),
                ('description', wagtail.wagtailcore.fields.RichTextField(default='', max_length=1024, verbose_name='description')),
                ('lokasi_donasi', wagtail.wagtailcore.fields.RichTextField(default='', max_length=1024, verbose_name='lokasi donasi')),
                ('tanggal_awal_donasi', models.DateField(default=datetime.date.today, verbose_name='tanggal awal donasi')),
                ('tanggal_akhir_donasi', models.DateField(default=datetime.date.today, verbose_name='tanggal akhir donasi')),
                ('dana_terkumpul', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='dana terkumpul')),
                ('dana_dibutuhkan', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='dana dibutuhkan')),
                ('status_donasi', models.CharField(default='status donasi belum didefinisikan', max_length=128, verbose_name='status donasi')),
                ('gallery_pic_url', models.CharField(blank=True, max_length=1024)),
                ('tag', models.CharField(default='', max_length=1024, verbose_name='tag')),
                ('gallery_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Gallery Pic')),
            ],
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128, unique=True, verbose_name='kategori status donasi')),
            ],
        ),
    ]
