# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 06:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='caption',
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='lokasi_event',
            field=wagtail.wagtailcore.fields.RichTextField(default='', max_length=1024, verbose_name='lokasi event'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='tag_event',
            field=models.CharField(default='', max_length=1024, verbose_name='tag event'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='waktu_event_berakhir',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='waktu akhir event'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='waktu_event_mulai',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='waktu mulai event'),
        ),
    ]
