# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20161021_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatemodel',
            name='nilai_donasi',
            field=models.IntegerField(default=0, verbose_name='nilai donasi'),
        ),
    ]
