# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20161102_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatemodel',
            old_name='user',
            new_name='donatur',
        ),
    ]
