# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_donatemodel_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryModel',
            new_name='ProjectModel',
        ),
    ]
