# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20161104_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_respon', models.CharField(default='', max_length=1024, verbose_name='kode respon')),
                ('status_respon', models.CharField(default='', max_length=1024, verbose_name='kode respon')),
                ('deskripsi_respon', wagtail.wagtailcore.fields.RichTextField(default='', max_length=1024, verbose_name='deskripsi respon')),
            ],
        ),
    ]
