# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20161202_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.CharField(max_length=1024, verbose_name='id project')),
                ('nama_donatur', models.CharField(default='anonim', max_length=1024, verbose_name='nama donatur')),
                ('alamat_donatur', models.CharField(default='', max_length=1024, verbose_name='alamat donatur')),
                ('email_donatur', models.CharField(default='', max_length=1024, verbose_name='email donatur')),
                ('handphone_donatur', models.CharField(default='', max_length=1024, verbose_name='handphone donatur')),
                ('nilai_donasi', models.IntegerField(default=0, verbose_name='nilai donasi')),
                ('status_pembayaran', models.CharField(default='belum terverifikasi', max_length=1024, verbose_name='status pembayaran')),
                ('tanggal_donasi', models.DateField(default=datetime.date.today, verbose_name='tanggal donasi')),
                ('jenis_bank', models.DateField(default='', max_length=1024, verbose_name='jenis bank')),
            ],
        ),
    ]
