# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_donationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationmodel',
            old_name='alamat_donatur',
            new_name='alamat',
        ),
        migrations.RenameField(
            model_name='donationmodel',
            old_name='email_donatur',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donationmodel',
            old_name='handphone_donatur',
            new_name='handphone',
        ),
        migrations.RenameField(
            model_name='donationmodel',
            old_name='nama_donatur',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='donationmodel',
            old_name='nilai_donasi',
            new_name='nilai',
        ),
        migrations.AddField(
            model_name='donationmodel',
            name='nomor_akun',
            field=models.CharField(default='', max_length=1024, verbose_name='nomor akun'),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='jenis_bank',
            field=models.CharField(default='', max_length=1024, verbose_name='jenis bank'),
        ),
    ]
