# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_auto_20161205_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='tanggal_donasi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
