# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 00:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_qnamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsciberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=1024, verbose_name='alamat email subscriber')),
                ('waktu_subscribe', models.DateField(default=datetime.date.today, verbose_name='waktu subscribe')),
            ],
        ),
    ]
