# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_subscibermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubsciberModel',
            new_name='SubscriberModel',
        ),
    ]
