# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_auto_20170203_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='role',
            field=models.CharField(choices=[('O', 'Project Owner'), ('D', 'Donatur'), ('V', 'Volunteer')], default='O', max_length=50, verbose_name='role'),
        ),
    ]
