# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0018_auto_20170302_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='role',
            field=models.CharField(choices=[('owner', 'Project Owner'), ('donatur', 'Donatur'), ('volunteer', 'Volunteer')], default='donatur', max_length=50, verbose_name='role'),
        ),
    ]
