# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-24 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0022_auto_20170302_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(default='', max_length=1024, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='city',
            field=models.CharField(default='', max_length=1024, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='country_code',
            field=models.CharField(default='', max_length=1024, verbose_name='country code'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='phone',
            field=models.CharField(default='', max_length=1024, verbose_name='phone'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='postal_code',
            field=models.CharField(default='', max_length=1024, verbose_name='postal code'),
        ),
    ]
