# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 07:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0023_auto_20170324_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(default=0, max_length=200, verbose_name='dana dibutuhkan')),
            ],
        ),
        migrations.CreateModel(
            name='RequestProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='', max_length=200, verbose_name='nama pengirim')),
                ('sender_email', models.CharField(default='', max_length=200, verbose_name='email pengirim')),
                ('phone', models.CharField(default='', max_length=1024, verbose_name='phone')),
                ('subject', models.CharField(default='', max_length=200, verbose_name='subject')),
                ('description', wagtail.wagtailcore.fields.RichTextField(default='', max_length=1024, verbose_name='description')),
                ('lokasi_project', wagtail.wagtailcore.fields.RichTextField(default='', max_length=1024, verbose_name='lokasi project')),
                ('requirements', models.CharField(choices=[('donasi', 'Donasi'), ('volunteer', 'Volunteer'), ('donasi volunteer', 'Donasi dan Volunteer')], default='donasi volunteer', max_length=1024, verbose_name='kebutuhan')),
                ('send_datetime', models.DateField(default=datetime.date.today, verbose_name='tanggal pengiriman')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_amount', models.CharField(default='', max_length=1024, verbose_name='phone')),
                ('volunteer_score', models.CharField(default='', max_length=1024, verbose_name='phone')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='lokasi_donasi',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='tanggal_akhir_donasi',
        ),
        migrations.RemoveField(
            model_name='projectmodel',
            name='tanggal_awal_donasi',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='id_project',
            field=models.CharField(default='', max_length=1024, verbose_name='id project'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='lokasi_project',
            field=wagtail.wagtailcore.fields.RichTextField(default='', max_length=1024, verbose_name='lokasi project'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='requirement',
            field=models.CharField(choices=[('donasi', 'Donasi'), ('volunteer', 'Volunteer'), ('donasi volunteer', 'Donasi dan Volunteer')], default='donasi volunteer', max_length=1024, verbose_name='kebutuhan'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='tanggal_akhir_project',
            field=models.DateField(default=datetime.date.today, verbose_name='tanggal akhir project'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='tanggal_awal_project',
            field=models.DateField(default=datetime.date.today, verbose_name='tanggal awal project'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='volunteer_dibutuhkan',
            field=models.CharField(default=0, max_length=200, verbose_name='volunteer dibutuhkan'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='volunteer_terkumpul',
            field=models.CharField(default=0, max_length=200, verbose_name='volunteer terkumpul'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='occupation',
            field=models.CharField(default='', max_length=1024, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='donatemodel',
            name='donatur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donatemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id_donations', to='gallery.ProjectModel'),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id_donate', to='gallery.ProjectModel'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='judul project'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='role',
            field=models.CharField(choices=[('owner', 'Project Owner'), ('donatur', 'Donatur'), ('volunteer', 'Volunteer'), ('donatur volunteer', 'Donatur dan Volunteer')], default='donatur volunteer', max_length=1024),
        ),
        migrations.AddField(
            model_name='userprofiledetailmodel',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id_profile', to='gallery.ProjectModel'),
        ),
        migrations.AddField(
            model_name='projectdetailmodel',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='gallery.ProjectModel'),
        ),
        migrations.AddField(
            model_name='projectdetailmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priorityprojectmodel',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id_priority', to='gallery.ProjectModel'),
        ),
        migrations.AddField(
            model_name='priorityprojectmodel',
            name='tanggal_awal_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanggal_awal_priority', to='gallery.ProjectModel'),
        ),
        migrations.AddField(
            model_name='priorityprojectmodel',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_priority', to='gallery.ProjectModel'),
        ),
    ]
