# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 07:50
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0024_auto_20170326_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='about',
            field=wagtail.wagtailcore.fields.RichTextField(default='', max_length=1024, verbose_name='deskripsi'),
        ),
    ]
