# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0025_auto_20170326_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='lokasi_event',
            field=models.CharField(default='', max_length=1024, verbose_name='lokasi event'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='lokasi_project',
            field=models.CharField(default='', max_length=1024, verbose_name='lokasi project'),
        ),
        migrations.AlterField(
            model_name='requestprojectmodel',
            name='lokasi_project',
            field=models.CharField(default='', max_length=1024, verbose_name='lokasi project'),
        ),
    ]
