# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 08:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0026_auto_20170326_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodel',
            name='status_donasi',
        ),
        migrations.AddField(
            model_name='projectdetailmodel',
            name='amount',
            field=models.CharField(default=0, max_length=200, verbose_name='jumlah donasi'),
        ),
        migrations.AddField(
            model_name='projectdetailmodel',
            name='midtrans_code',
            field=models.CharField(default=0, max_length=1024, verbose_name='kode midtrans'),
        ),
        migrations.AddField(
            model_name='projectdetailmodel',
            name='status_donasi',
            field=models.CharField(default='status donasi belum didefinisikan', max_length=1024, verbose_name='status donasi'),
        ),
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_id_detail', to='gallery.ProjectModel'),
        ),
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='score',
            field=models.CharField(default=0, max_length=200, verbose_name='volunteer score'),
        ),
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project_detail_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofiledetailmodel',
            name='donate_amount',
            field=models.CharField(default='', max_length=1024, verbose_name='donate amount'),
        ),
        migrations.AlterField(
            model_name='userprofiledetailmodel',
            name='volunteer_score',
            field=models.CharField(default='', max_length=1024, verbose_name='volunteer score'),
        ),
    ]
