# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0027_auto_20170326_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='amount',
            field=models.IntegerField(default=0, max_length=200, verbose_name='jumlah donasi'),
        ),
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='midtrans_code',
            field=models.CharField(default='', max_length=150, verbose_name='kode midtrans'),
        ),
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='score',
            field=models.IntegerField(default=0, max_length=200, verbose_name='volunteer score'),
        ),
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='status_donasi',
            field=models.CharField(default='undefined', max_length=150, verbose_name='status donasi'),
        ),
    ]
