# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0028_auto_20170326_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='jumlah donasi'),
        ),
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='score',
            field=models.IntegerField(default=0, verbose_name='volunteer score'),
        ),
    ]
