# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0030_remove_projectmodel_id_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiledetailmodel',
            name='id_project',
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='telephone',
            field=models.CharField(default='', max_length=200, verbose_name='telephone donatur'),
        ),
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_detail_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='dana_dibutuhkan',
            field=models.IntegerField(default=0, verbose_name='dana dibutuhkan'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='dana_terkumpul',
            field=models.IntegerField(default=0, verbose_name='dana terkumpul'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='lokasi_project',
            field=models.CharField(default='', max_length=200, verbose_name='lokasi project'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='requirement',
            field=models.CharField(choices=[('donasi', 'Donasi'), ('volunteer', 'Volunteer'), ('donasi volunteer', 'Donasi dan Volunteer')], default='donasi volunteer', max_length=200, verbose_name='kebutuhan'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='volunteer_dibutuhkan',
            field=models.IntegerField(default=0, verbose_name='volunteer dibutuhkan'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='volunteer_terkumpul',
            field=models.IntegerField(default=0, verbose_name='volunteer terkumpul'),
        ),
        migrations.AlterField(
            model_name='requestprojectmodel',
            name='lokasi_project',
            field=models.CharField(default='', max_length=200, verbose_name='lokasi project'),
        ),
        migrations.AlterField(
            model_name='requestprojectmodel',
            name='phone',
            field=models.CharField(default='', max_length=200, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='requestprojectmodel',
            name='requirements',
            field=models.CharField(choices=[('donasi', 'Donasi'), ('volunteer', 'Volunteer'), ('donasi volunteer', 'Donasi dan Volunteer')], default='donasi volunteer', max_length=200, verbose_name='kebutuhan'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='country_code',
            field=models.CharField(default='', max_length=200, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='occupation',
            field=models.CharField(default='', max_length=200, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone',
            field=models.CharField(default='', max_length=200, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='postal_code',
            field=models.CharField(default='', max_length=200, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='role',
            field=models.CharField(choices=[('owner', 'Project Owner'), ('donatur', 'Donatur'), ('volunteer', 'Volunteer'), ('donatur volunteer', 'Donatur dan Volunteer')], default='donatur volunteer', max_length=200),
        ),
        migrations.DeleteModel(
            name='UserProfileDetailModel',
        ),
    ]
