# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0031_auto_20170326_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorityprojectmodel',
            name='id_project',
        ),
        migrations.RemoveField(
            model_name='priorityprojectmodel',
            name='tanggal_awal_project',
        ),
        migrations.RemoveField(
            model_name='priorityprojectmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='priority_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='tanggal_awal_priority',
            field=models.DateField(default=datetime.date.today, verbose_name='tanggal awal priority'),
        ),
        migrations.DeleteModel(
            name='PriorityProjectModel',
        ),
    ]
