# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0032_auto_20170326_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatemodel',
            name='donatur',
        ),
        migrations.RemoveField(
            model_name='donatemodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='donationmodel',
            name='id_project',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='gambar_event',
        ),
        migrations.DeleteModel(
            name='ResponseModel',
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='requirement',
            field=models.CharField(choices=[('donasi', 'Donasi'), ('volunteer', 'Volunteer'), ('donasi_volunteer', 'Donasi dan Volunteer')], default='donasi_volunteer', max_length=200, verbose_name='kebutuhan'),
        ),
        migrations.AlterField(
            model_name='requestprojectmodel',
            name='requirements',
            field=models.CharField(choices=[('donasi', 'Donasi'), ('volunteer', 'Volunteer'), ('donasi_volunteer', 'Donasi dan Volunteer')], default='donasi_volunteer', max_length=200, verbose_name='kebutuhan'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='role',
            field=models.CharField(choices=[('owner', 'Project Owner'), ('donatur', 'Donatur'), ('volunteer', 'Volunteer'), ('donatur_volunteer', 'Donatur dan Volunteer')], default='donatur_volunteer', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DonateModel',
        ),
        migrations.DeleteModel(
            name='DonationModel',
        ),
        migrations.DeleteModel(
            name='EventModel',
        ),
    ]
