# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0033_auto_20170327_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='about',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, default='', max_length=1024, verbose_name='deskripsi'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='postal code'),
        ),
    ]
