# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0036_volunteerstatusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetailmodel',
            name='midtrans_code',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='kode midtrans'),
        ),
    ]
